apiVersion: templates.weave.works/v1alpha1
kind: GitOpsSet
metadata:
  name: api-namespaces
  annotations:
    metadata.weave.works/description: "This GitOps Set shows off RBAC capabilities.  Here the service account does not have permissions to create namespace objects via the gitops sets controller, you have a lot of control over this powerful controller."
spec:
  generators:
    - list:
        elements:
          - name: public-api-v1
          - name: public-api-legacy
          - name: mobile-api-v1
          - name: mobile-api-v2
  templates:
    - content:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ .Element.name }}"
        