apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oidc-auth
  namespace: flux-system
stringData:
  clientID: ${dexClientId:=weave-gitops-enterprise}
  clientSecret: B7Skl2cfSoOQgOhIkeqxx1uJjWxjCFoEEymk
  issuerURL: https://${dexDomain}
  redirectURL: https://${gitopsDomain}/oauth2/callback
