apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise
spec:
  releaseName: weave-gitops-enterprise
  targetNamespace: flux-system
  chart:
    spec:
      chart: mccp
      version: ">= 0.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-clusters-weave-gitops-enterprise-charts
        namespace: flux-system
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      annotations:
        beta.cloud.google.com/backend-config: '{"default": "enterprise-lb-backend-config"}'
        networking.gke.io/v1beta1.FrontendConfig: enterprise-lb-frontend-config
    ingress:
      enabled: true
      annotations:
        networking.gke.io/managed-certificates: ${cert_name:=gitops-cert}
      hosts:
      - host: ${gitopsDomain}
        paths:
        - path: /*
          pathType: ImplementationSpecific
    config:
      capi:
        clusters:
          namespace: flux-system
    tls:
      enabled: false
