apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-enterprise
spec:
  releaseName: weave-gitops-enterprise
  targetNamespace: flux-system
  chart:
    spec:
      chart: mccp
      version: ">= 0.0.0-0"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-clusters-weave-gitops-enterprise-charts
        namespace: flux-system
  interval: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
  values:
    service:
      annotations:
        beta.cloud.google.com/backend-config: '{"default": "enterprise-lb-backend-config"}'
        networking.gke.io/v1beta1.FrontendConfig: enterprise-lb-frontend-config
    ingress:
      enabled: true
      annotations:
        networking.gke.io/managed-certificates: ${cert_name:=gitops-cert}
      hosts:
      - host: ${gitopsDomain}
        paths:
        - path: /*
          pathType: ImplementationSpecific
    config:
      capi:
        repositoryURL: https://github.com/weaveworks/weave-gitops-clusters
      oidc:
        enabled: true
        issuerURL: https://${dexDomain}
        redirectURL: https://${gitopsDomain}/oauth2/callback
        clientCredentialsSecret: oidc-auth
    policy-agent:
      enabled: true
      config:
        accountId: weaveworks
        clusterId: ${policyAgentClusterId:=wge-dev}
        admission:
          enabled: false
        audit:
          enabled: true
    pipeline-controller:
      controller:
        manager:
          image:
            tag: pr-180-watches
      promotion:
        retry:
          delay: 3
          maxDelay: 30
          threshold: 5
        rateLimit:
          value: 30
          interval: 60
        service:
          enabled: true
          annotations:
            beta.cloud.google.com/backend-config: '{"default": "pipeline-promotion-lb-backend-config"}'
            networking.gke.io/v1beta1.FrontendConfig: pipeline-promotion-lb-frontend-config
        ingress:
          enabled: true
          annotations:
            networking.gke.io/managed-certificates: ${promotions_cert_name:=promotions-cert}
          hosts:
          - host: promotions.${gitopsDomain}
            paths:
            - path: /*
              pathType: ImplementationSpecific
    tls:
      enabled: false
    enablePipelines: true
    enableTerraformUI: true
    enableRunUI: true
    enableExplorer: false
    templates-controller:
      enabled: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-gitops-enterprise-pipeline-controller-role
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weave-gitops-enterprise-pipeline-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-gitops-enterprise-pipeline-controller-role
subjects:
- kind: ServiceAccount
  name: weave-gitops-enterprise-pipeline-controller
  namespace: flux-system
