apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: ${cert_name:=gitops-cert}
spec:
  domains:
    - ${gitopsDomain}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: ${promotions_cert_name:=promotions-cert}
spec:
  domains:
    - promotions.${gitopsDomain}
