---
#
# department-engineering-employees@weave.works
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weave-engineers-gitops-reader
roleRef:
  kind: ClusterRole
  name: gitops-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: department-corporate-it@weave.works
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: department-dx-employees@weave.works
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: department-product-employees@weave.works
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: department-engineering-employees@weave.works
    apiGroup: rbac.authorization.k8s.io
---
#
# static admin
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-static-user-wge-admin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: admin@test.invalid
    apiGroup: rbac.authorization.k8s.io
---
#
# static read-only
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-static-user-wge-ro
roleRef:
  kind: ClusterRole
  name: gitops-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: ro@test.invalid
    apiGroup: rbac.authorization.k8s.io
