#
# admin
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-static-user-wge-admin
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: admin@test.invalid
    apiGroup: rbac.authorization.k8s.io
---
#
# read-only
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-static-user-wge-ro
roleRef:
  kind: ClusterRole
  name: gitops-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: ro@test.invalid
    apiGroup: rbac.authorization.k8s.io
