$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weave-gitops-readonly-ro
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view-ro
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wego-admin-cluster-role-admin
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-gitops-readonly
# #
# # admin
# #
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: dex-static-user-wge-admin
# roleRef:
#   kind: ClusterRole
#   name: app-manager-role
#   apiGroup: rbac.authorization.k8s.io
# subjects:
#   - kind: User
#     name: admin@test.invalid
#     apiGroup: rbac.authorization.k8s.io
# ---
