apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
spec:
  releaseName: tf-controller
  targetNamespace: flux-system
  chart:
    spec:
      chart: tf-controller
      version: '>=0.9.3'
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
  interval: 1h0s
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    concurrency: 24
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 64Mi
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    image:
      tag: v0.15.1
    runner:
      image:
        tag: v0.15.1
    awsPackage:
      tag: v4.38.0-v1alpha11
    branchPlanner:
      enabled: true
