apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - flagger.yaml
  - istio.yaml
  - podinfo.yaml
  - weave-gitops.yaml
  - weave-gitops-enterprise.yaml
