apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - flagger.yaml
  - nginx.yaml
  - istio.yaml
  - dex.yaml
  - weave-gitops.yaml
  - weave-gitops-enterprise.yaml
  # - podinfo.yaml # this source is in k8s/apps/gitops/podinfo so the ns-admin user can be demonstrated with some permissions
