---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@github.com:22/weaveworks/weave-gitops-enterprise.git
  ref:
    branch: main
  secretRef:
    name: weave-gitops-enterprise-deploy-key
