---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-policy-agent
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-policy-agent
      sourceRef:
        kind: HelmRepository
        name: profiles-catalog
        namespace: flux-system
      version: 0.3.x
  releaseName: weave-policy-agent
  targetNamespace: policy-system
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    accountId: weaveworks
    clusterId: internal-dev
