---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: profiles-catalog
  namespace: flux-system
spec:
  interval: 10m
  url: https://raw.githubusercontent.com/weaveworks/weave-gitops-profile-examples/gh-pages
