apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.1.3"
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 1m
