apiVersion: ENC[AES256_GCM,data:9kQ=,iv:Cd9nw3G34Rv3iT+umJCENLw5Lb/arLzB2jtk4jC0oDE=,tag:z4/o1VhZHUYX5w5IMTGrcA==,type:str]
data:
    password: ENC[AES256_GCM,data:6onZ37zNL+hoRcyFMMibMscFE5IzWhqAm0b/Eb8VFSsNhvzcYWWmwm44yNRgczc5kHWvg3mp9tnv5kwRpzePPTDy+I/+OWWLaU5mIwpbuww=,iv:q6rqNgqnZz1dJPA5ZRSolkQ7UopASNrxa8B6WklJRZI=,tag:uG8nwI4iQ4Nvo6XEG7Ifqw==,type:str]
    username: ENC[AES256_GCM,data:MUzGkwkVoAjvBw8+8ZV2uQ==,iv:y3yRjcLMmeCxRBMw4Qb40K4TOAMCVmtLwL7Dt5Rx8x0=,tag:U3rBD/RTlUCUMsEasOpNxg==,type:str]
kind: ENC[AES256_GCM,data:fJ/jWihq,iv:t0pyzJS7IYDP94e4mBvMeedeMeQpeUk96VpJU0ZmJjI=,tag:1KkAKTWcywPj8f2v+bhavA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:vIsiF4NxiQXoluZY9HcuKwQ=,iv:+V8ddIdFHAoU1GxgzmrxFECuj8jlil0SdahPJu/FxFs=,tag:bQm+eAXNmy9/2ZcMXyUJPQ==,type:str]
    namespace: ENC[AES256_GCM,data:5qC5ga5OqwySUsw=,iv:e2MmQ3JccVuTOInomWiVlQ6Hd+KmZFvrYHSCDCHQG2U=,tag:THNfCZDbRsO0N7eg/Frqsw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/weave-gitops-clusters/locations/global/keyRings/weave-gitops/cryptoKeys/weave-gitops-sops
          created_at: "2022-07-29T16:58:52Z"
          enc: CiQAWSZaInI+rHl72WaUHfM+fzaqu1FxAsftOv7cL3c1wxEe7/cSSQCqoc1JMRmO86vTBNKVlSU3CXoYPv8MePxO/qAZu/Bh7BLeR2+iIBFzGJsEgCO8xA7X/Mn6BOXCzGCklhHONdfD72P6Y24MdlY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-29T16:58:53Z"
    mac: ENC[AES256_GCM,data:0lXUCTNXoNfGmD2tokPKG69EzCY5NPdqfcBnaiNcVSy03w5mGAn8R+zWszn8VTrViZyjnBgugDdkxQK8K8Piw1n/bumCNUlfouV+GBRTJebmWK7JqVAwtOhMQzNhKrHyUyV8sdwmGePKI8k/YrFYgmziLyd2ElMS+W+bnZTmdAM=,iv:CgjWzUgatPYIPtA4hvZsgEb/25gJWakB3ri0ZqH3lp4=,tag:YXT4gvmHbVEvTEI8yzI3ag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
