apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector # could be .spec.values.explorer.collector.serviceAccount.name
rules:
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "clusterroles", "rolebindings", "clusterrolebindings" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "kustomize.toolkit.fluxcd.io" ]
    resources: [ "kustomizations" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "helm.toolkit.fluxcd.io" ]
    resources: [ "helmreleases" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "source.toolkit.fluxcd.io" ]
    resources: [ "buckets", "helmcharts", "gitrepositories", "helmrepositories", "ocirepositories" ]
    verbs: [ "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector # could be .spec.values.explorer.collector.serviceAccount.name
subjects:
  - kind: ServiceAccount
    name: collector # should match .spec.values.explorer.collector.serviceAccount.name
    namespace: flux-system # should match .spec.values.explorer.collector.serviceAccount.namespace
roleRef:
  kind: ClusterRole
  name: collector # name of the cluster role created earlier
  apiGroup: rbac.authorization.k8s.io