apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weave-gitops-enterprise
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/clusters/internal-dev-gke/wge
  # path: ./k8s/apps/base/weave-gitops-enterprise
  prune: true
  validation: client
