---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-enterprise
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/apps/enterprise
  prune: true
  validation: client
  decryption:
    provider: sops # required for dex auth decryption
  postBuild:
    substitute:
      dexClientId: weave-gitops-enterprise
      dexDomain: dex.internal-dev.wego-gke.weave.works
      gitopsDomain: gitops.internal-dev.wego-gke.weave.works
      policyAgentClusterId: internal-dev
    substituteFrom:
      - kind: Secret
        name: iap-oauth-client
