---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-enterprise
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/apps/enterprise
  prune: true
  validation: client
  postBuild:
    substitute:
      ingress_host: gitops.internal-dev.wego-gke.weave.works
