---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: shared-secrets
    - name: cluster-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure
  prune: true
  validation: client
  postBuild:
    substitute:
      apexDomain: dev-internal.wego-gke.weave.works
      txtOwnerId: dev-internal
      externalDnsSa: dns-internal-dev-gke@weave-gitops-clusters.iam.gserviceaccount.com
