---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: shared-secrets
    - name: cluster-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure
  prune: true
  validation: client
  patches:
    - patch: |-
        - op: replace
          path: /spec/values/serviceAccount/annotations/iam.gke.io~1gcp-service-account
          value: dns-internal-dev-gke@weave-gitops-clusters.iam.gserviceaccount.com
        - op: replace
          path: /spec/values/txtOwnerId
          value: dev-internal
        - op: replace
          path: /spec/values/domainFilters
          value: ["dev-internal.wego-gke.weave.works"]
      target:
        kind: HelmRelease
        name: external-dns-controller
