apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pipelines-vcluster
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: clusters
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/clusters/internal-dev-gke/pipelines-vcluster
  prune: true
