apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pipelines
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: prod-kubeconfig
  interval: 10m0s
  dependsOn:
    - name: clusters
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/clusters/internal-dev-gke/pipelines
  prune: true
