apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: quickstart
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: clusters
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/clusters/internal-dev-gke/quickstart
  prune: true
