apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-vcluster
    templates.weave.works/template-namespace: default
  name: test
  namespace: default
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/weave-gitops-clusters\",\"head_branch\":\"wge-create-branch-2xdjq\",\"title\":\"Create resource test\",\"description\":\"This PR creates a cluster-template-vcluster instance\",\"template_name\":\"cluster-template-vcluster\",\"parameter_values\":{\"CLUSTER_NAME\":\"test\",\"KUBERNETES_VERSION\":\"1.25.0\"},\"commit_message\":\"Create cluster-template-vcluster instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
spec:
  capiClusterRef:
    name: test

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-vcluster
    templates.weave.works/template-namespace: default
  name: test
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: test

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/weave-gitops-clusters\",\"head_branch\":\"wge-create-branch-2xdjq\",\"title\":\"Create resource test\",\"description\":\"This PR creates a cluster-template-vcluster instance\",\"template_name\":\"cluster-template-vcluster\",\"parameter_values\":{\"CLUSTER_NAME\":\"test\",\"KUBERNETES_VERSION\":\"1.25.0\"},\"commit_message\":\"Create cluster-template-vcluster instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
  labels:
    templates.weave.works/template-name: cluster-template-vcluster
    templates.weave.works/template-namespace: default
  name: test
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: ""
      repo: ""
      version: ""
    values: |-
      service:
        type: NodePort
  kubernetesVersion: 1.25.0
