apiVersion: pipelines.weave.works/v1alpha1
kind: Pipeline
metadata:
  name: podinfo-01
  namespace: flux-system
spec:
  appRef:
    apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: helmrelease
    name: podinfo
  environments:
    - name: dev
      targets:
        - namespace: podinfo-01-dev
          clusterRef:
            kind: GitopsCluster
            name: dev
            namespace: flux-system
    - name: prod
      targets:
        - namespace: podinfo-01-prod
          clusterRef:
            kind: GitopsCluster
            name: prod
            namespace: default
  promotion:
    pull-request:
      url: https://github.com/weaveworks/weave-gitops-clusters
      secretRef:
        name: promotion-credentials
