apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- patch: |-
    - op: add
      path: /metadata/annotations/iam.gke.io~1gcp-service-account
      value: sops-decrypter-weave-gitops@weave-gitops-clusters.iam.gserviceaccount.com
  target:
    kind: ServiceAccount
    name: kustomize-controller
- patch: |
    - op: add
      path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/eventSources/items/properties/kind/enum/-
      value: Pipeline
  target:
    kind: CustomResourceDefinition
    name:  alerts.notification.toolkit.fluxcd.io
 
