---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-gitops
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/apps/gitops
  prune: true
  validation: client
  decryption:
    provider: sops # required for dex auth decryption
  postBuild:
    substitute:
      apexDomain: euw1.wego-gke.weave.works
      dexDomain: dex.euw1.wego-gke.weave.works
      gitopsDomain: gitops.euw1.wego-gke.weave.works
      dexSecret: B7Skl2cfSoOQgOhIkeqxx1uJjWxjCFoEEymk
    substituteFrom:
      - kind: Secret
        name: iap-oauth-client
