---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: shared-secrets
    - name: cluster-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure
  prune: true
  postBuild:
    substitute:
      apexDomain: euw1.wego-gke.weave.works
      txtOwnerId: euw1
      externalDnsSa:  dns-europe-west1-gke@weave-gitops-clusters.iam.gserviceaccount.com
