---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: shared-secrets
    - name: cluster-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infrastructure
  prune: true
  validation: client
