apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 10m
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
