#
# These are here so that they apply correctly (otherwise it's attempted to
# apply them in the dex namespace and that isn't what we want)
#
# namespace-readonly
#
# Bind the weave-gitops-readonly role AND the 'view' roles
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podinfo-ns-weave-gitops-readonly-ns-ro
  namespace: podinfo
roleRef:
  kind: ClusterRole
  name: weave-gitops-readonly
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: ns-ro@test.invalid
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podinfo-ns-view-ns-ro
  namespace: podinfo
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: ns-ro@test.invalid
    apiGroup: rbac.authorization.k8s.io
---
#
# namespace-admin
#
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podinfo-ns-wego-admin-cluster-role-ns-admin
  namespace: podinfo
roleRef:
  kind: ClusterRole
  name: wego-admin-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: User
    name: ns-admin@test.invalid
    apiGroup: rbac.authorization.k8s.io
