apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo-policy
  namespace: default
spec:
  imageRepositoryRef:
    name: podinfo-repo
  policy:
    semver:
      range: 5.0.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: example-kubeconfig
  namespace: default
spec:
  filterTags:
    extract: $ts
    pattern: ^dev-branch-[a-f0-9]+-(?P<ts>[0-9]+)
  imageRepositoryRef:
    name: howto-kubeconfig-dev
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo-v1beta2
  namespace: default
spec:
  imageRepositoryRef:
    name: podinfo-v1beta2
  policy:
    semver:
      range: 0.x.x
