apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: leaf-cluster-config
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/config/leaf-cluster
  prune: true
  validation: client
  postBuild:
    substitute:
      managementClusterName: internal-dev
