apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - load-balancer.yaml
  - tls-cert.yaml
  - readonly-cluster-role.yaml
  - release.yaml
  - dex-google-auth-creds.yaml
