#
# Make a non-iap LB for dex
#

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: dex-lb-backend-config
  namespace: dex
spec:
  healthCheck:
    # Make sure this isn't a path that will 404
    requestPath: '/healthz'
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: dex-lb-frontend-config
  namespace: dex
spec:
  redirectToHttps:
    enabled: true
