apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-vcluster
    templates.weave.works/template-namespace: default
  name: leaf-04
  namespace: default
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/weave-gitops-clusters\",\"head_branch\":\"wge-create-branch-vxr71\",\"base_branch\":\"main\",\"title\":\"Create resource leaf-04\",\"description\":\"This PR creates a cluster-template-vcluster instance\",\"name\":\"cluster-template-vcluster\",\"parameter_values\":{\"CLUSTER_NAME\":\"leaf-04\",\"KUBERNETES_VERSION\":\"1.25.0\"},\"commit_message\":\"Create cluster-template-vcluster instance\",\"credentials\":{},\"namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"clusters/management/clusters/default/leaf-04.yaml\"]}"
spec:
  capiClusterRef:
    name: leaf-04

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-vcluster
    templates.weave.works/template-namespace: default
  name: leaf-04
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: leaf-04
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: leaf-04

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weaveworks/weave-gitops-clusters\",\"head_branch\":\"wge-create-branch-vxr71\",\"base_branch\":\"main\",\"title\":\"Create resource leaf-04\",\"description\":\"This PR creates a cluster-template-vcluster instance\",\"name\":\"cluster-template-vcluster\",\"parameter_values\":{\"CLUSTER_NAME\":\"leaf-04\",\"KUBERNETES_VERSION\":\"1.25.0\"},\"commit_message\":\"Create cluster-template-vcluster instance\",\"credentials\":{},\"namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"clusters/management/clusters/default/leaf-04.yaml\"]}"
  labels:
    templates.weave.works/template-name: cluster-template-vcluster
    templates.weave.works/template-namespace: default
  name: leaf-04
  namespace: default
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  helmRelease:
    chart:
      name: ""
      repo: ""
      version: ""
    values: |-
      syncer:
        extraArgs:
        - --tls-san=leaf-04.default.svc
      service:
        type: NodePort
  kubernetesVersion: 1.25.0
