---
apiVersion: capi.weave.works/v1alpha1
kind: CAPITemplate
metadata:
  name: go-templating-example
  namespace: default
spec:
  description: "This template shows off some go-templating. It has a `renderType: templating`"
  renderType: templating
  params:
    - name: CLUSTER_NAME
      description: This is used for the cluster naming.
      options: []
      required: true
    - name: USE_TEST_SUBNET
      description: boolean string
      options: ["true", "false"]
      required: false
  resourcetemplates:
    - apiVersion: cluster.x-k8s.io/v1alpha3
      kind: Cluster
      metadata:
        name: "{{ .params.CLUSTER_NAME }}"
      spec:
        clusterNetwork:
          pods:
            cidrBlocks:
              - '{{ if eq .params.USE_TEST_SUBNET "true" }}192.168.0.0/16{{ else }}192.168.1.0/16{{ end }}'
        infrastructureRef:
          apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
          kind: AWSCluster
          name: "{{ .params.CLUSTER_NAME }}"
        controlPlaneRef:
          kind: KubeadmControlPlane
          apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
          name: "{{ .params.CLUSTER_NAME }}-control-plane"
