apiVersion: clustertemplates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: podinfo-pipeline
  namespace: default
  annotations: # may be able to remove following https://github.com/weaveworks/weave-gitops-enterprise/issues/1730
    templates.weave.works/profiles-enabled: false
    templates.weave.works/kustomizations-enabled: false
    templates.weave.works/credentials-enabled: false
  labels:
    weave.works/template-type: pipeline #used to determine 'Type'
spec:
  description: PoT for re-creating podinfo-pipeline
  params:
  #metadata
    - name: PIPELINE_NAME
      description: [Test](https://docs.gitops.weave.works)
    - name: PIPELINE_NAMESPACE
      description: Namespace for Pipeline (flux-system)
  #Appdata
    - name: APPLICATION_NAME
      description: Name of the HelmRelease for your application (podinfo)
  resourcetemplates:
    - apiVersion: pipelines.weave.works/v1alpha1
      kind: ${PIPELINE_NAME}
      metadata:
        name: ${PIPELINE_NAME}
        namespace: ${PIPELINE_NAMESPACE}
      spec:
        appRef:
          apiVersion: helm.toolkit.fluxcd.io/v2beta1
          kind: HelmRelease
          name: ${APPLICATION_NAME}
        environments:
        - name: dev
          targets:
            - namespace: ${PIPELINE_NAME}-dev
              clusterRef:
                kind: GitopsCluster
                name: dev
                namespace: flux-system
        - name: test
          targets:
            - namespace: ${PIPELINE_NAME}-qa
              clusterRef:
                kind: GitopsCluster
                name: dev
                namespace: flux-system
            - namespace:  ${PIPELINE_NAME}-perf
              clusterRef:
                kind: GitopsCluster
                name: dev
                namespace: flux-system
        - name: prod
          targets:
            - namespace: ${PIPELINE_NAME}-prod
              clusterRef:
                kind: GitopsCluster
                name: prod
                namespace: default
