apiVersion: templates.weave.works/v1alpha1
kind: GitOpsTemplate
metadata:
  name: pipeline-notification-resources
  namespace: flux-system
  labels:
    weave.works/template-type: application # These are generic Flux resources rather than Pipeline-specific
spec:
  description: Creates flux notification controller resources for a cluster, required for promoting applications via pipelines.
  params:
    # Pipeline parameters
    - name: RESOURCE_NAME 
      description: Name for the generated objects, should match the target Application (HelmRelease) name.
    - name: RESOURCE_NAMESPACE # Required parameter name for a valid template
      description: Namespace for the generated objects, should match the target Application (HelmRelease) namespace.
    - name: HOST_URL # Required parameter name for a valid template
      description: Exposed URL for the promotion webhook on the management cluster
    - name: PROVIDER_TYPE
      options: ["generic", "generic-hmac"]
      description: Choose between unauthenticated (generic) and authenticate (generic-hmac) communication with promotion webhook 
    - name: ENV_NAME
      description: Environment the cluster is a part of within a pipeline.
    - name: SECRET_REF
      description: Required credentials for HMAC PROVIDER_TYPE
      default: null
      required: false
  resourcetemplates:
  - apiVersion: notification.toolkit.fluxcd.io/v1beta1
    kind: Provider
    metadata:
      name: ${RESOURCE_NAME}
      namespace: ${RESOURCE_NAMESPACE}
    spec:
      address: http://${HOST_URL}/default/${APP_NAME}/${ENV_NAME}
      type: ${PROVIDER_TYPE}
      secretRef: ${SECRET_REF}
  - apiVersion: notification.toolkit.fluxcd.io/v1beta1
    kind: Alert
    metadata:
      name: ${RESOURCE_NAME}
      namespace: ${RESOURCE_NAMESPACE}
    spec:
      providerRef:
        name: ${RESOURCE_NAME}
      eventSeverity: info
      eventSources:
        - kind: HelmRelease
          name: ${RESOURCE_NAME}
      exclusionList:
        - ".*upgrade.*has.*started"
        - ".*is.*not.*ready"
        - "^Dependencies.*"
