apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.0.0" # {"$promotion": "flux-system:podinfo-01:prod"}
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 1m
