apiVersion: ENC[AES256_GCM,data:moc=,iv:THY0x4IeSsU18Om5ukRdcb/WXiNEZCajruiX2+DXoP4=,tag:uY8IDhK1YRefMySse5L8aQ==,type:str]
kind: ENC[AES256_GCM,data:mXXBLin3,iv:T+2Bh0F4Ju4MkdkZaBWbwyDaaSdrHZTS+/2st1qt+XM=,tag:54/iUk6RENwpI84UC3a5uQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QwNMJ9jIHNnKqVQzjjNsTg==,iv:qUNO/tNqz+Mws9Q4fpKwjkEPATMKTcC4pTrrmhsdPVU=,tag:rnCiJA+ZiPGwnA/gm/MdSQ==,type:str]
    namespace: ENC[AES256_GCM,data:hGePIjEIHe4I5c8=,iv:sjdL5HyTQ32cfVRzycMw2zPCBrY0XrInG2WrwFc7izc=,tag:Q4DA+L4X01cBHRBfCue9nw==,type:str]
data:
    client_id: ENC[AES256_GCM,data:lsa9bOy0rt+PT8y6ZBuanpyf1xk80wKHz+PCeJQVvlP7s2JV6DCG1/VV8cpGS5aSiTELOh6yeR1jHo75W+5qlqxa1BjZ+umWd/3o6FBALH4gakiq0LxsdRmw07gP8QUg,iv:MzKkZ2LPgC29k8fOT8jrET9vs3tQUgRNb2hMk7vwXpA=,tag:wx7POWV6YGLnMxe90uLYpg==,type:str]
    client_secret: ENC[AES256_GCM,data:SW+bpWukluQrnehccfcZWxeY55MuCS44/rmtnd39VqILl1IkcX5F/jP3QRdHRUPZ,iv:a4a+nZP3tTxZ6Q/Qp2VW9ZdUF1Q81t/IGSE/W1DVRkU=,tag:7rXUVQsJ0TUAnZqHevKt/w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/weave-gitops-clusters/locations/global/keyRings/weave-gitops/cryptoKeys/weave-gitops-sops
          created_at: "2022-04-01T16:32:04Z"
          enc: CiQAWSZaItA6GcNx45Xdc1oKOvmS0qa8tDe2edv8seC7AOgT+IkSSQCqoc1JP6uw0Z9QLguc2HG8xO0viuNky2H0/Lgt6icbP9NS4DR8Y3twL0V9nS4NxoHZU+wLKpe805h+RjMU3YjVrQNYOsTdKlQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-05T12:26:59Z"
    mac: ENC[AES256_GCM,data:xcrtMXmu4wEmaixzVXtkwXPArgmUvyIr+BkdzejaMCWIcjoxGXgINygwEeldjnz6BBiuFmEcBBi9X4PEvZVLpmwmzmp2AZa0TowshNKsj6EGiCMY1KsQmeSkfDRZ6vWiLNUrDjWKNB0l7h/nAtJE1OCjGCBSUR+9TFBSzVMpCJE=,iv:2RsG+6GFqCpD6X4E9pdpvhbe2P0cseQ+BP3QgTKwisY=,tag:RPLCI/N64oQ/aKkvC4pcxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
