apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-app
spec:
  releaseName: weave-gitops-app
  targetNamespace: flux-system
  chart:
    spec:
      chart: charts/gitops-server
      sourceRef:
        kind: GitRepository
        name: weave-gitops
        namespace: flux-system
      version: "1.0.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      # FIXME gitops-server -> weave-gitops-app
      repository: europe-west1-docker.pkg.dev/weave-gitops-clusters/weave-gitops/gitops-server # {"$imagepolicy": "flux-system:weave-gitops-app:name"}
      tag: 1648756624-aa50dee917b45a949ce3b8bf8ec2171e49cc3490 # {"$imagepolicy": "flux-system:weave-gitops-app:tag"}
    # FIXME? handle TLS @ that LB?
    additionalArgs: ["--insecure"]
    adminUser:
      create: true
      username: test-admin
      password: some-super-secret-password
