apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m0s
  path: ./kustomize
  prune: true
  targetNamespace: podinfo
  sourceRef:
    kind: GitRepository
    name: podinfo
    namespace: flux-system
