apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: weave-gitops-app
  namespace: flux-system
spec:
  image: europe-west1-docker.pkg.dev/weave-gitops-clusters/weave-gitops/gitops-server
  interval: 5m0s

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name:  weave-gitops-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: weave-gitops-app
  policy:
    numerical:
      order: asc
  filterTags:
    # Match and interpret the pattern set here:
    # https://github.com/weaveworks/weave-gitops/blob/6effbc30f134a1f6bb02344e1e71e49af53140f4/.github/workflows/pr.yaml#L167
    pattern: '^(?P<unixtime>[0-9]*)-[0-9a-fA-F]*$'
    extract: '$unixtime'

---

# This covers all imagePolicies in the namespace
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: weaveworksbot
        email: weaveworksbot@users.noreply.github.com
      messageTemplate: |
        k8s/apps/base/weave-gitops-app: Automated image update

        Update images in:
        {{ range $resource, $_ := .Updated.Objects -}}
        - {{ $resource.Kind | lower }} {{ $resource.Name | lower  }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./k8s/apps/base/weave-gitops-app
    strategy: Setters
