---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: weave-gitops-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: weave-gitops
  endpoints:
  - port: http-metrics
    interval: 30s
