apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops-app
spec:
  releaseName: weave-gitops-app
  targetNamespace: flux-system
  chart:
    spec:
      chart: charts/gitops-server
      sourceRef:
        kind: GitRepository
        name: weave-gitops
        namespace: flux-system
      version: "1.0.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  values:
    # cf. https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
    envVars:
      - name: WEAVE_GITOPS_FEATURE_TELEMETRY
        value: "true"
    image:
      repository: europe-west1-docker.pkg.dev/weave-gitops-clusters/weave-gitops/gitops-server # {"$imagepolicy": "flux-system:weave-gitops-app:name"}
      tag: 1669289529-c005e1abfbe91e0681bb84d690af891114be43ab # {"$imagepolicy": "flux-system:weave-gitops-app:tag"}
    adminUser:
      create: true
      username: test-admin
      passwordHash: $2y$10$sHT5PLEDTGWSwde/DfOZveOFcjAHy5ap37s6cyV7z6i2Ca6KMygUy
    oidcSecret:
      create: true
      clientID: weave-gitops-app
      clientSecret: ${dexSecret}
      issuerURL: https://${dexDomain}
      redirectURL: https://${gitopsDomain}/oauth2/callback
    additionalArgs: ["--insecure"]
    service:
      annotations:
        beta.cloud.google.com/backend-config: '{"default": "weave-gitops-app-lb-backend-config"}'
        networking.gke.io/v1beta1.FrontendConfig: weave-gitops-app-lb-frontend-config
    # Enable ingress (we don't set a type b/c GKE magics that)
    ingress:
      enabled: true
      annotations:
        networking.gke.io/managed-certificates: gitops-cert # must match name tls-certs.yaml
      hosts:
        - host: ${gitopsDomain}
          paths:
            - path: /*
              pathType: ImplementationSpecific # ImplementationSpecific => let the lb decide
    metrics:
      enabled: true
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 64Mi
